### ISSUE TITLE
Gradle compile issue in @carployee/cfalert

### ISSUE THREAD

**Issue by KunaalMangal** [Firetrip/carployee-cfalert#1]
**Hello** !
**@flodaniel** ,
       I am **KUNAAL MANGAL**. I am creating this issue because I am facing this in my NativeScript project which I have upgraded from NativeScript 6 to NativeScript 8. I am facing a problem related to adding/declaring Gradle dependency configuration using Compile method. Change this **compile method to API or Implementation** as compile method is deprecated in Gradle 7.0. You can see the official documentation of Gradle for reference from the given link :-
  https://docs.gradle.org/current/userguide/upgrading_version_6.html
  
  
![image](https://user-images.githubusercontent.com/47212486/217415601-b18c905d-4533-446d-aa35-3f18b97470df.png)

**Comment by flodaniel** [comment]
Hi @KunaalMangal,

i am no longer maintaining this package. Feel free to fork it and work from there :)
